import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import ts from 'typescript';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
const require = createRequire(import.meta.url);
const load = (file, mocks = {}) => {
  const code = ts.transpileModule(readFileSync(file, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true } }).outputText;
  const module = { exports: {} };
  new Function('require', 'module', 'exports', code)(name => name in mocks ? mocks[name] : require(name), module, module.exports);
  return module.exports;
};
let checks=0;
const test=async(name,run)=>{await run();checks++;console.log('PASS '+name);};
const guides=JSON.parse(readFileSync('docs/operations/2026-public-course-guides.json')).courses;
const model=load('src/lib/course-guide/model.ts');
const offerings=guides.filter(c=>c.offering_id).map(c=>({...c,id:c.offering_id,status:'ARCHIVED',starts_on:'2026-07-01',ends_on:'2026-07-31'}));
const courses=model.mergeCatalog(guides,offerings);
await test('16 source courses deduplicate the three linked operational offerings',()=>assert.equal(courses.length,16));
await test('new public offerings remain discoverable',()=>assert.equal(model.mergeCatalog(guides,[...offerings,{...offerings[0],id:'new-offering'}]).length,17));
await test('Korean spaced certificate search finds matching course',()=>assert.equal(model.filterCatalog(courses,model.catalogFilters({q:'시니어 요리 지도사'}))[0].id,'2026-silver-food'));
await test('mode filter, empty results and whitespace search are correct',()=>{assert.equal(model.filterCatalog(courses,model.catalogFilters({mode:'ONLINE'})).length,0);assert.equal(model.filterCatalog(courses,model.catalogFilters({q:'   '})).length,16);});
await test('query arrays and invalid modes cannot break render',()=>assert.deepEqual(model.catalogFilters({q:['a','b'],mode:'invalid',view:['list']}),{q:'',mode:'',view:'cards'}));
await test('view URL preserves and safely encodes query and mode',()=>{const url=model.catalogHref(model.catalogFilters({q:'목공 & test',mode:'OFFLINE'}),'list');const p=new URL(url,'http://localhost').searchParams;assert.equal(p.get('q'),'목공 & test');assert.equal(p.get('view'),'list');assert.equal(p.get('mode'),'OFFLINE');});
let dbError=null,throwDb=false;
const selections=[];
const query={select(v){selections.push(v);return this;},eq(){return this;},order(){return this;},maybeSingle:async()=>({data:guides[0],error:dbError}),then(resolve){resolve({data:dbError?null:guides,error:dbError});}};
const api=load('src/lib/course-guide/data.ts',{'./model':model,'@/lib/supabase/server':{createServerSupabaseClient:async()=>{if(throwDb)throw Error('network');return{from:()=>query};}},'@/lib/portal/data':{getCourseCards:async()=>({offerings,unavailable:false})}});
await test('DB-backed catalog reads guides and preserves linked deduplication',async()=>{assert.equal((await api.getCourseCatalog()).courses.length,16);assert(selections.every(s=>!s.includes('*')));});
await test('failed DB guides report partial availability',async()=>{dbError={message:'unavailable'};const r=await api.getCourseCatalog();assert.equal(r.unavailable,true);assert.equal(r.courses.length,3);await assert.rejects(api.getCourseGuide('2026-manual-therapy'),/불러오지/);dbError=null;});
await test('connection failure handled and invalid detail IDs not queried',async()=>{throwDb=true;assert.equal((await api.getCourseCatalog()).unavailable,true);assert.equal(await api.getCourseGuide('../bad'),null);throwDb=false;});
const portalData={modeLabel:{OFFLINE:'대면',ONLINE:'온라인',BLENDED:'혼합'},getCourseIntroduction:async()=>null};
const Link=({children,scroll,...props})=>React.createElement('a',props,children);
const ui=load('src/components/portal/ui.tsx',{'next/link':Link,'@/lib/portal/data':portalData});
const catalog=load('src/components/course-guide/catalog.tsx',{'next/link':Link,'@/lib/portal/data':portalData});
let unavailable=false;
const page=load('src/app/courses/page.tsx',{'next/link':Link,'@/lib/course-guide/data':{getCourseCatalog:async()=>({courses,unavailable})},'@/lib/course-guide/model':model,'@/components/course-guide/catalog':catalog,'@/components/portal/ui':ui}).default;
const render=async params=>renderToStaticMarkup(await page({searchParams:Promise.resolve(params)}));
await test('default cards render all16 links and certificate labels',async()=>{const html=await render({});assert.equal((html.match(/data-course-card/g)??[]).length,16);assert(html.includes('시니어요리지도사'));assert(html.includes('xl:grid-cols-4'));assert(html.includes('aria-current="page"'));});
await test('list is accessible table with all16 courses and retained form view',async()=>{const html=await render({view:'list'});assert.equal((html.match(/scope="row"/g)??[]).length,16);assert(html.includes('role="region"'));assert(html.includes('name="view" value="list"'));assert(!html.includes('data-course-card'));});
await test('zero results and partial data are not misleading',async()=>{assert((await render({q:'no-matching-course'})).includes('조건에 맞는'));unavailable=true;assert((await render({})).includes('일부 교육과정을'));unavailable=false;});
let detail=guides[0];
const detailPage=load('src/app/courses/[id]/page.tsx',{'next/link':Link,'next/navigation':{notFound:()=>{throw Error('404');}},'@/lib/course-guide/data':{getCourseGuide:async()=>detail},'@/lib/portal/data':portalData,'@/components/portal/ui':ui}).default;
await test('details show pending dates and schedule history without opening admissions',async()=>{const html=renderToStaticMarkup(await detailPage({params:Promise.resolve({id:detail.id})}));assert(html.includes('2026년 12월 예정'));assert(html.includes('일정 변경 안내'));assert(html.includes('관련 자격증 미기재'));assert(!html.includes('/apply'));});
await test('unknown or unpublished details return404',async()=>{detail=null;await assert.rejects(detailPage({params:Promise.resolve({id:'private'})}),/404/);});
console.log(`${checks} course catalog checks passed.`);
